In [54]:
import numpy as np
import pandas as pd
import scipy

In [55]:
x = 5
y = 6
print(x+y)

my_string = "Python"
print(my_string)

11
Python


In [13]:
len(my_string)

6

In [16]:
print("my " + my_string + " is level " + str(x))

my Python is level 5


In [22]:
my_string[0], my_string[2], my_string[0:2], my_string[-1::-2]

('P', 't', 'Py', 'nhy')

In [23]:
my_string.upper(), my_string.replace("y", "yy"), my_string.find("y")

('PYTHON', 'Pyython', 1)

In [30]:
colors = ["red","blue","green"]
print(colors[0])
colors.append("yellow")
print(colors)
colors.insert(1, "pink")  # insert at any position
print(colors)
colors.pop(1)      # remove an element
print(colors)
print(colors.index("green"))   # search for an element

red
['red', 'blue', 'green', 'yellow']
['red', 'pink', 'blue', 'green', 'yellow']
['red', 'blue', 'green', 'yellow']
2


In [31]:
x = 10
if x == 5:
    print("'Y'")
else:
    print("N")

N


In [32]:
a = [2,3,5,7]
for element in a:
    print(a)

[2, 3, 5, 7]
[2, 3, 5, 7]
[2, 3, 5, 7]
[2, 3, 5, 7]


In [33]:
my_tuple =("price", 5.7)
print(len(my_tuple))
print(my_tuple[1])

2
5.7


In [19]:
# numpy arrany

my_array = np.array([1,2,3,4])
print(len(my_array))
my_array[my_array>2]

4


array([3, 4])

In [48]:
my_array.sum(),my_array.max(), my_array.mean()   #aggregation

(10, 4, 2.5)

In [50]:
my_array=np.array([1,2,2,4,5])   # remove duplicate
np.unique(my_array)

array([1, 2, 4, 5])

In [53]:
np.append(my_array,6), np.insert(my_array,3,3), np.delete(my_array,[1])  # add/remove

(array([1, 2, 2, 4, 5, 6]), array([1, 2, 2, 3, 4, 5]), array([1, 2, 4, 5]))

In [ ]:
# Panda dataframe

In [30]:
df = pd.DataFrame(
    {
        "cust_id" : ["A","B","C"],
        "date": ["5/1/2017", "5/8/2017","5/22/2017"],
        "spend": [10,5,20]
        
    },
    # index
    columns = ["cust_id", "date", "spend"]
)

#describe table
df.shape

(3, 3)

In [60]:
# subset columns
df["spend"]   # an array

0    10
1     5
2    20
Name: spend, dtype: int64

In [62]:
df[["spend"]]  # a dataframe

spend
0     10
1      5
2     20

In [63]:
df[["cust_id","spend"]]

cust_id  spend
0       A     10
1       B      5
2       C     20

In [69]:
# subset rows
df.sample(n=1)    # random 

cust_id      date  spend
0       A  5/1/2017     10

In [70]:
df.head(n=3)

cust_id       date  spend
0       A   5/1/2017     10
1       B   5/8/2017      5
2       C  5/22/2017     20

In [ ]:
# pandas data I/O

In [61]:
# from csv  "C:\Users\grace\Downloads\BA501_python_data.csv"
file_location = "/Users/grace//Downloads/"
file_name = "BA501_python_data.csv"
my_data = pd.read_csv(file_location + file_name)

my_data.head(10)

country      date  experiment_id              order_id  spend_usd  \
0      JP  20170402       12624548   5813140433216629693  16.138855   
1      US  20170403       12624549  16333056276711034931   9.990000   
2      JP  20170404       12624548  11227119161741298366  19.887087   
3      US  20170403       12624548  11927299833124210932  19.990000   
4      JP  20170403       12624549  11644727017708872749  88.220093   
5      FR  20170406       12624548   2887851716418524034  10.641677   
6      US  20170406       12624548   8835194413765780524   9.990000   
7      US  20170402       12624549   2761291987218019434  10.090000   
8      US  20170405       12624548   9027895522629963459   9.990000   
9      US  20170405       12624548   2588200289165850850  19.990000   

                user_id      vertical  
0   5006730028073359543  ANDROID_APPS  
1   5938685669571545259  ANDROID_APPS  
2  17623708458399141713  ANDROID_APPS  
3  18042812344456618148  ANDROID_APPS  
4   4325104700699531031  ANDROID_APPS  
5  15563614621402392174  ANDROID_APPS  
6    793284520969747371  ANDROID_APPS  
7   4877509876568871706         MUSIC  
8   3647559719307779196  ANDROID_APPS  
9   3647559719307779196  ANDROID_APPS

In [17]:
my_data[(my_data.country == "JP")].head(5)  # selsect column

country      date  experiment_id              order_id  spend_usd  \
0       JP  20170402       12624548   5813140433216629693  16.138855   
2       JP  20170404       12624548  11227119161741298366  19.887087   
4       JP  20170403       12624549  11644727017708872749  88.220093   
12      JP  20170402       12624549   1931426249776431110   5.379618   
41      JP  20170401       12624549   7104670035152263784   5.379618   

                 user_id      vertical  
0    5006730028073359543  ANDROID_APPS  
2   17623708458399141713  ANDROID_APPS  
4    4325104700699531031  ANDROID_APPS  
12   1925282073030462007  ANDROID_APPS  
41  13151664051368694565  ANDROID_APPS

In [18]:
my_data[["user_id","date","spend_usd"]].head(5)

user_id      date  spend_usd
0   5006730028073359543  20170402  16.138855
1   5938685669571545259  20170403   9.990000
2  17623708458399141713  20170404  19.887087
3  18042812344456618148  20170403  19.990000
4   4325104700699531031  20170403  88.220093

In [7]:
my_data["user_id"].head(5)

0     5006730028073359543
1     5938685669571545259
2    17623708458399141713
3    18042812344456618148
4     4325104700699531031
Name: user_id, dtype: uint64

In [69]:
my_data["country"]

15381     AE
22250     AE
19088     AE
38119     AE
22092     AE
17146     AR
68222     AR
68224     AR
17147     AR
49877     AR
68220     AR
68221     AR
49876     AR
49878     AR
68223     AR
1163      AT
1888      AT
2834      AT
4682      AT
4684      AT
5645      AT
7642      AT
7643      AT
7645      AT
7646      AT
8206      AT
8868      AT
8869      AT
9780      AT
9781      AT
        ... 
49082     ZA
50034     ZA
52916     ZA
53978     ZA
54709     ZA
54950     ZA
57628     ZA
63575     ZA
66107     ZA
68793     ZA
68796     ZA
68799     ZA
68804     ZA
68811     ZA
69308     ZA
69758     ZA
72633     ZA
72634     ZA
32917    NaN
32922    NaN
32925    NaN
32918    NaN
32923    NaN
32916    NaN
32919    NaN
32920    NaN
32921    NaN
32926    NaN
32915    NaN
32924    NaN
Name: country, Length: 73910, dtype: object

In [22]:
my_data[1:10]  # select rows

country      date  experiment_id              order_id  spend_usd  \
1      US  20170403       12624549  16333056276711034931   9.990000   
2      JP  20170404       12624548  11227119161741298366  19.887087   
3      US  20170403       12624548  11927299833124210932  19.990000   
4      JP  20170403       12624549  11644727017708872749  88.220093   
5      FR  20170406       12624548   2887851716418524034  10.641677   
6      US  20170406       12624548   8835194413765780524   9.990000   
7      US  20170402       12624549   2761291987218019434  10.090000   
8      US  20170405       12624548   9027895522629963459   9.990000   
9      US  20170405       12624548   2588200289165850850  19.990000   

                user_id      vertical  
1   5938685669571545259  ANDROID_APPS  
2  17623708458399141713  ANDROID_APPS  
3  18042812344456618148  ANDROID_APPS  
4   4325104700699531031  ANDROID_APPS  
5  15563614621402392174  ANDROID_APPS  
6    793284520969747371  ANDROID_APPS  
7   4877509876568871706         MUSIC  
8   3647559719307779196  ANDROID_APPS  
9   3647559719307779196  ANDROID_APPS

In [23]:
my_data[(my_data.user_id == 7250841187939126009) & (my_data.country == "JP")]

Empty DataFrame
Columns: [country, date, experiment_id, order_id, spend_usd, user_id, vertical]
Index: []

In [25]:
my_data[["user_id","date","spend_usd"]][(my_data.user_id == 7250841187939126009) & (my_data.country == "JP")]

Empty DataFrame
Columns: [user_id, date, spend_usd]
Index: []

In [27]:
# create new columns
my_data["spend_usd_whole"] = my_data["spend_usd"]*5
my_data.head(5)

country      date  experiment_id              order_id  spend_usd  \
0      JP  20170402       12624548   5813140433216629693  16.138855   
1      US  20170403       12624549  16333056276711034931   9.990000   
2      JP  20170404       12624548  11227119161741298366  19.887087   
3      US  20170403       12624548  11927299833124210932  19.990000   
4      JP  20170403       12624549  11644727017708872749  88.220093   

                user_id      vertical  spend_usd_whole  
0   5006730028073359543  ANDROID_APPS        80.694275  
1   5938685669571545259  ANDROID_APPS        49.950000  
2  17623708458399141713  ANDROID_APPS        99.435435  
3  18042812344456618148  ANDROID_APPS        99.950000  
4   4325104700699531031  ANDROID_APPS       441.100465

In [28]:
# drop column
my_data = my_data.drop("spend_usd_whole", axis = 1)
my_data.head(5)

country      date  experiment_id              order_id  spend_usd  \
0      JP  20170402       12624548   5813140433216629693  16.138855   
1      US  20170403       12624549  16333056276711034931   9.990000   
2      JP  20170404       12624548  11227119161741298366  19.887087   
3      US  20170403       12624548  11927299833124210932  19.990000   
4      JP  20170403       12624549  11644727017708872749  88.220093   

                user_id      vertical  
0   5006730028073359543  ANDROID_APPS  
1   5938685669571545259  ANDROID_APPS  
2  17623708458399141713  ANDROID_APPS  
3  18042812344456618148  ANDROID_APPS  
4   4325104700699531031  ANDROID_APPS

In [64]:
# change data type, date into date format
my_data.date = pd.to_datetime(my_data.date, format='%Y%m%d')
my_data.head(4)

country       date  experiment_id              order_id  spend_usd  \
15381      AE 2017-04-03       12624548   8078410735682954089   1.984784   
22250      AE 2017-04-04       12624549   6754390085836948239   0.977429   
19088      AE 2017-04-05       12624549  13528583286475944786  10.071074   
38119      AE 2017-04-05       12624548  18081415353723908788   0.952926   

                    user_id      vertical  
15381  15342218896746506117  ANDROID_APPS  
22250  11276568206142884528  ANDROID_APPS  
19088  10187980296635197684  ANDROID_APPS  
38119    921275339006250633  ANDROID_APPS

In [49]:
# groupby(), select country, sum(spend_usd) from a group by 1, and rest the index
result = my_data.groupby(["country"])["spend_usd"].sum().reset_index()
result

country      spend_usd
0       AE      14.963641
1       AR      16.180000
2       AT    3759.115467
3       AU   15877.633679
4       BE    2789.523098
5       BR    7226.139306
6       CA   12951.332762
7       CH    3549.431644
8       CZ       4.982100
9       DE   31491.686018
10      DK    1358.179783
11      DZ       1.990000
12      EG       1.432207
13      ES    6280.247879
14      FI    1458.194388
15      FR   21180.562013
16      GB   22644.965632
17      GR     803.236874
18      HK   10188.606958
19      HR       1.290010
20      HU      15.460824
21      ID    5480.962275
22      IE    1160.637553
23      IL      12.082609
24      IN    2393.356750
25      IS       2.490535
26      IT    9360.671022
27      JP  241406.864175
28      KR  131706.979622
29      KW      12.960000
30      LV       2.111318
31      MX      52.039831
32      MY       8.604777
33      NL    4226.217002
34      NO    1842.916416
35      NZ    1871.535585
36      OM       2.970000
37      PK       1.992930
38      PL    2555.709180
39      PR       4.990000
40      PT     604.500019
41      RO       2.123098
42      RS      19.990000
43      RU      26.615652
44      SA      63.867151
45      SE    2634.859729
46      SG    4706.505418
47      SK       6.371211
48      TH      40.363124
49      TR    3909.707246
50      TW      16.797751
51      UA      43.914211
52      US  234252.713573
53      VN       3.990000
54      ZA    2402.150305

In [63]:
# order by: sort values()
my_data = my_data.sort_values(['country','date'],ascending=[True, True])
my_data.head(5)

country      date  experiment_id              order_id  spend_usd  \
15381      AE  20170403       12624548   8078410735682954089   1.984784   
22250      AE  20170404       12624549   6754390085836948239   0.977429   
19088      AE  20170405       12624549  13528583286475944786  10.071074   
38119      AE  20170405       12624548  18081415353723908788   0.952926   
22092      AE  20170407       12624549  18156435304744752611   0.977428   

                    user_id      vertical  
15381  15342218896746506117  ANDROID_APPS  
22250  11276568206142884528  ANDROID_APPS  
19088  10187980296635197684  ANDROID_APPS  
38119    921275339006250633  ANDROID_APPS  
22092   5956003464692123193  ANDROID_APPS

In [67]:
# Join: merge()
# pd.merge(left_table, right_table,how='left',on='x1','x2')

# Union: concat()--left/right combine, stack()--like Union all, more important!!
# pd.concat([left_table, right_table])
# pd.stack([upper_table, lower_table])